// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ8BPL9TJNmurjHp9BA31HtuRyFpMnh0Y',
    appId: '1:488733899314:android:7db9bb0ade06a08ab3da2b',
    messagingSenderId: '488733899314',
    projectId: 'pocket-garage-f0760',
    storageBucket: 'pocket-garage-f0760.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS2Mmz9FXcJD919ntPMJncETsxtmNuGFo',
    appId: '1:488733899314:ios:b4275f6fa56d4823b3da2b',
    messagingSenderId: '488733899314',
    projectId: 'pocket-garage-f0760',
    storageBucket: 'pocket-garage-f0760.firebasestorage.app',
    iosBundleId: 'com.example.pocketGarageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS2Mmz9FXcJD919ntPMJncETsxtmNuGFo',
    appId: '1:488733899314:ios:b4275f6fa56d4823b3da2b',
    messagingSenderId: '488733899314',
    projectId: 'pocket-garage-f0760',
    storageBucket: 'pocket-garage-f0760.firebasestorage.app',
    iosBundleId: 'com.example.pocketGarageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt8m1ggm3gxxpK2WvzAfkCiP-r7o0S6Jo',
    appId: '1:488733899314:web:cc8d4c6218f0b45fb3da2b',
    messagingSenderId: '488733899314',
    projectId: 'pocket-garage-f0760',
    authDomain: 'pocket-garage-f0760.firebaseapp.com',
    storageBucket: 'pocket-garage-f0760.firebasestorage.app',
  );
}
